# Generated by Django 3.0 on 2020-09-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoagro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='publish_date',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='mensaje',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
